spring:
  application:
    name: dev.ai

server:
  port: 11435

ollama:
  modelName: qwen3:8b
  baseUrl: http://localhost:11434
  timeout: 120000
  temperature: 0.7
  topP: 0.95
  topK: 3
  logRequests: true
  logResponses: true

pkm:
  obsidian:
    file-system-path: /Users/lucas.farias/obsidian
  logseq:
    rag:
      enabled: false
    server-url: http://127.0.0.1:12315/api
    authorization-token: 0432483b-469a-4ca6-b16d-35106294b36e
  rag:
    summaries:
      enabled: false