spring:
  application:
    name: dev.ai
  output:
    ansi:
      enabled: always
server:
  port: 11435

management:
  endpoints:
    web:
      base-path: /
  server:
    port: 53411

ollama:
  modelName: qwen3:8b
  baseUrl: http://localhost:11434
  timeout: 120000
  temperature: 0.7
  topP: 0.95
  topK: 25
  logRequests: true
  logResponses: true

guardrails:
  input:
    rag-only.enabled: true
    check-input.enabled: true
  output:
    check-facts.enabled: false

re-rank:
  enabled: true
  path-to-model: "/Users/lucas.farias/workspace/pocs/ms-marco-MiniLM-L6-v2/onnx/model.onnx"
  path-to-tokenizer: "/Users/lucas.farias/workspace/pocs/ms-marco-MiniLM-L6-v2/tokenizer.json"
  max-result: 25
  min-score: 0.25

pkm:
  obsidian:
    enabled: false
    file-system-path: /Users/lucas.farias/obsidian
  logseq:
    enabled: true
    server-url: http://127.0.0.1:12315/api
    authorization-token: 0432483b-469a-4ca6-b16d-35106294b36e
